name: Scoreboard-ReRevision
author: HeyItsRed
version: 1.0.1
main: heyits.red.Scoreboard.rr.Main
description: Lightweight nonflickering scoreboard revision
softdepend: [PlaceholderAPI]
commands:
  sb:
    description: Scoreboard main command