name: Scoreboard-ReRevision
author: HeyItsRed
version: 1.0.4
main: heyits.red.Scoreboard.rr.Main
description: Lightweight nonflickering scoreboard revision
softdepend: [PlaceholderAPI]
softdepend: [MVdWPlaceholderAPI]
commands:
  sb:
    description: Scoreboard main command