name: Scoreboard-ReRevision
author: HeyItsRed
version: 1.0.7
main: heyits.red.Scoreboard.rr.Main
description: Lightweight nonflickering scoreboard revision
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
commands:
  sb:
    description: Scoreboard main command